// Auto-generated by server.js — do not edit
import type { EnvConfig } from './types'

export const ENV: EnvConfig = {
  GATEWAY_TOKEN: "df435097607c95c88fccb0dcb5c72699c4b2686d34d4ed3d",
  GATEWAY_HOST: "localhost",
  GATEWAY_PORT: 18789,
  GATEWAY_SECURE: false,
  SERVER_DEVICE_ID: "c4d41079f70f1824d1e3294135754c87a62de47e8ba6c8f72a08e82c7412ac5e",
  SERVER_PUBLIC_KEY: "pVIduTm_C4F7rgSxa__ZIzJY_1xbkFtBz6W7lYXrJ9U",
  RELAY_WS_URL: "ws://192.168.4.200:9090"
}
