// Auto-generated by server.js — do not edit
import type { EnvConfig } from './types'

export const ENV: EnvConfig = {
  GATEWAY_TOKEN: "d00e03138a579940c3ca6c44c481b0411c322f8fc20f3d6f",
  GATEWAY_HOST: "localhost",
  GATEWAY_PORT: 18789,
  GATEWAY_SECURE: false,
  SERVER_DEVICE_ID: "908c9eab89e3e8233924d955a8ec545fdcf0bdbd228ccbf4b68a56d274fcf99b",
  SERVER_PUBLIC_KEY: "ZZW0gBnM5wUMpx5BaEbD3hI9xvM6VEZDjdvb1Iuc0kw",
  SERVER_PRIVATE_KEY: "byIo2TBtZlg0dAvMXl-OMHsyQtY3zvH-xCMD0twhp3I",
  RELAY_WS_URL: "ws://192.168.4.202:9090"
}
