// server.js — Unified server: static files + env config + WebSocket relay
// Replaces: libp2p circuit relay with plain WebSocket message broker

import { createServer } from 'http'
import { readFileSync, writeFileSync, existsSync, statSync } from 'fs'
import { join, extname } from 'path'
import { homedir, networkInterfaces } from 'os'
import { fileURLToPath } from 'url'
import { dirname } from 'path'
import WebSocket, { WebSocketServer } from 'ws'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const SERVE_PORT = parseInt(process.env.PORT || '8080', 10)
const RELAY_PORT = parseInt(process.env.RELAY_PORT || '9090', 10)
const FEDERATION_SECRET = process.env.FEDERATION_SECRET || ''

// ===== Networking Helpers =====

function getLanIp() {
  const ifaces = networkInterfaces()
  for (const name of Object.keys(ifaces)) {
    for (const iface of ifaces[name] ?? []) {
      if (iface.family === 'IPv4' && !iface.internal) {
        return iface.address
      }
    }
  }
  return null
}

// ===== Config (replaces generate-env.sh) =====

function generateEnvJs(relayWsUrl = '') {
  const configPath = join(homedir(), '.openclaw', 'openclaw.json')
  const identityPath = join(homedir(), '.openclaw', 'identity', 'device.json')

  let token = ''
  let gwHost = 'localhost'
  let gwPort = 18789
  let gwSecure = false
  let serverDeviceId = ''
  let serverPublicKey = ''

  // Read gateway config
  if (existsSync(configPath)) {
    try {
      const config = JSON.parse(readFileSync(configPath, 'utf8'))
      const gw = config.gateway || {}
      token = gw.auth?.token || ''
      gwHost = 'localhost'
      gwPort = gw.port || 18789
      gwSecure = (gw.tailscale?.mode || 'off') !== 'off'
    } catch (err) {
      console.error('Failed to read gateway config:', err.message)
    }
  } else {
    console.warn(`Gateway config not found: ${configPath}`)
  }

  // Read server identity
  if (existsSync(identityPath)) {
    try {
      const identity = JSON.parse(readFileSync(identityPath, 'utf8'))
      serverDeviceId = identity.deviceId || ''

      if (identity.publicKeyPem) {
        const pem = identity.publicKeyPem
        const lines = pem.trim().split('\n').filter(l => !l.startsWith('-----'))
        const rawB64 = lines.join('')
        const der = Buffer.from(rawB64, 'base64')
        const rawKey = der.subarray(-32)
        serverPublicKey = rawKey.toString('base64url')
      }

      console.log(`Found server identity: ${serverDeviceId.slice(0, 16)}...`)
    } catch (err) {
      console.error('Failed to read server identity:', err.message)
    }
  } else {
    console.warn(`Server identity not found: ${identityPath}`)
  }

  const safeStr = (s) => JSON.stringify(String(s))
  const envContent = `// Auto-generated by server.js — do not edit
import type { EnvConfig } from './types'

export const ENV: EnvConfig = {
  GATEWAY_TOKEN: ${safeStr(token)},
  GATEWAY_HOST: ${safeStr(gwHost)},
  GATEWAY_PORT: ${Number(gwPort) || 18789},
  GATEWAY_SECURE: ${Boolean(gwSecure)},
  SERVER_DEVICE_ID: ${safeStr(serverDeviceId)},
  SERVER_PUBLIC_KEY: ${safeStr(serverPublicKey)},
  RELAY_WS_URL: ${safeStr(relayWsUrl)}
}
`

  writeFileSync(join(__dirname, 'src', 'lib', 'env.ts'), envContent)
  console.log(`Wrote src/lib/env.ts (port=${gwPort}, secure=${gwSecure})`)

  return { gwPort, gwSecure }
}

// ===== Static File Serving (replaces Apache httpd) =====

const MIME_TYPES = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.mjs': 'application/javascript',
  '.ts': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.webmanifest': 'application/manifest+json',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.ttf': 'font/ttf'
}

function createStaticServer() {
  const distDir = join(__dirname, 'dist')

  const server = createServer(async (req, res) => {
    // Production: serve from dist/
    let urlPath = req.url.split('?')[0]
    if (urlPath === '/') urlPath = '/index.html'

    const filePath = join(distDir, urlPath)

    // Security: prevent path traversal
    if (!filePath.startsWith(distDir)) {
      res.writeHead(403)
      res.end('Forbidden')
      return
    }

    try {
      const stat = statSync(filePath)
      if (!stat.isFile()) throw new Error('Not a file')

      const ext = extname(filePath)
      const contentType = MIME_TYPES[ext] || 'application/octet-stream'

      const content = readFileSync(filePath)

      const isHashed = urlPath.startsWith('/assets/')
      const cacheControl = isHashed
        ? 'public, max-age=31536000, immutable'
        : 'public, max-age=0, must-revalidate'

      res.writeHead(200, {
        'Content-Type': contentType,
        'Content-Length': content.length,
        'Cache-Control': cacheControl
      })
      res.end(content)
    } catch {
      try {
        const indexPath = join(distDir, 'index.html')
        const content = readFileSync(indexPath)
        res.writeHead(200, {
          'Content-Type': 'text/html',
          'Content-Length': content.length,
          'Cache-Control': 'public, max-age=0, must-revalidate'
        })
        res.end(content)
      } catch {
        res.writeHead(404)
        res.end('Not Found')
      }
    }
  })

  return server
}

// ===== WebSocket Relay (with federation) =====

function startRelayServer(peerRelayUrls = []) {
  /** @type {Map<string, { ws: import('ws').WebSocket, displayName: string }>} */
  const clients = new Map()

  /** @type {Map<import('ws').WebSocket, { remotePeers: Map<string, string> }>} */
  const fedLinks = new Map()

  /** @type {Set<{ ws: import('ws').WebSocket, reconnectTimer: ReturnType<typeof setTimeout> | null, stopped: boolean }>} */
  const outboundFedLinks = new Set()

  const wss = new WebSocketServer({ port: RELAY_PORT })

  // ---- Peer list helpers ----

  function getLocalPeers() {
    return Array.from(clients.entries()).map(([peerId, info]) => ({
      peerId, displayName: info.displayName
    }))
  }

  function getRemotePeers() {
    const seen = new Set()
    const result = []
    for (const [, link] of fedLinks) {
      for (const [peerId, displayName] of link.remotePeers) {
        if (!clients.has(peerId) && !seen.has(peerId)) {
          seen.add(peerId)
          result.push({ peerId, displayName })
        }
      }
    }
    return result
  }

  function broadcastPeerList() {
    const peers = [...getLocalPeers(), ...getRemotePeers()]
    const msg = JSON.stringify({ type: 'peers', peers })
    for (const [, info] of clients) {
      if (info.ws.readyState === 1) info.ws.send(msg)
    }
  }

  function sendLocalPeersToFedLinks() {
    const msg = JSON.stringify({ type: 'federation:peers', peers: getLocalPeers() })
    for (const [ws] of fedLinks) {
      if (ws.readyState === 1) ws.send(msg)
    }
  }

  function forwardToFedLinks(data) {
    const str = typeof data === 'string' ? data : String(data)
    for (const [ws] of fedLinks) {
      if (ws.readyState === 1) ws.send(str)
    }
  }

  // ---- Handle federation messages ----

  function handleFedMessage(ws, raw) {
    let msg
    try { msg = JSON.parse(String(raw)) } catch { return }

    if (msg.type === 'federation:peers') {
      const link = fedLinks.get(ws)
      if (!link) return
      link.remotePeers.clear()
      for (const p of msg.peers || []) {
        link.remotePeers.set(p.peerId, p.displayName || '')
      }
      broadcastPeerList()
      return
    }

    // Forward chat/presence to all local clients
    if (msg.type === 'chat' || msg.type === 'presence') {
      const data = String(raw)
      for (const [, info] of clients) {
        if (info.ws.readyState === 1) info.ws.send(data)
      }
      return
    }

    // Forward DM to specific local client, or to another federation link
    if (msg.type === 'dm') {
      const recipient = msg.recipient
      if (!recipient) return

      // Try local client first
      const target = clients.get(recipient)
      if (target && target.ws.readyState === 1) {
        target.ws.send(String(raw))
        return
      }

      // Forward to federation link that has this peer (not the sender link)
      for (const [fedWs, link] of fedLinks) {
        if (fedWs === ws) continue
        if (link.remotePeers.has(recipient) && fedWs.readyState === 1) {
          fedWs.send(String(raw))
          return
        }
      }
      return
    }
  }

  // ---- Local client connections ----

  wss.on('connection', (ws) => {
    let registeredPeerId = null
    let isFederation = false

    ws.on('message', (raw) => {
      let msg
      try { msg = JSON.parse(String(raw)) } catch { return }

      // Federation handshake (must be first message)
      if (msg.type === 'federation:hello' && !registeredPeerId && !isFederation) {
        if (FEDERATION_SECRET && msg.secret !== FEDERATION_SECRET) {
          console.warn('[federation] inbound link rejected: invalid secret')
          ws.close(4001, 'Invalid federation secret')
          return
        }
        isFederation = true
        fedLinks.set(ws, { remotePeers: new Map() })
        ws.send(JSON.stringify({ type: 'federation:peers', peers: getLocalPeers() }))
        console.log('[federation] inbound link established')
        return
      }

      if (isFederation) {
        handleFedMessage(ws, raw)
        return
      }

      // Regular client registration
      if (msg.type === 'register') {
        registeredPeerId = msg.peerId || null
        if (!registeredPeerId) return
        clients.set(registeredPeerId, { ws, displayName: msg.displayName || '' })
        console.log(`[relay] registered: ${registeredPeerId.slice(0, 16)}... (${msg.displayName || 'anonymous'})`)
        broadcastPeerList()
        sendLocalPeersToFedLinks()
        return
      }

      if (!registeredPeerId) return

      if (msg.type === 'chat' || msg.type === 'presence') {
        const data = String(raw)
        for (const [peerId, info] of clients) {
          if (peerId === registeredPeerId) continue
          if (info.ws.readyState === 1) info.ws.send(data)
        }
        forwardToFedLinks(data)
        return
      }

      if (msg.type === 'dm') {
        const recipient = msg.recipient
        if (!recipient) return

        // Try local client first
        const target = clients.get(recipient)
        if (target && target.ws.readyState === 1) {
          target.ws.send(String(raw))
          return
        }

        // Forward to federation link that has this peer
        for (const [fedWs, link] of fedLinks) {
          if (link.remotePeers.has(recipient) && fedWs.readyState === 1) {
            fedWs.send(String(raw))
            return
          }
        }
        return
      }
    })

    ws.on('close', () => {
      if (isFederation) {
        fedLinks.delete(ws)
        broadcastPeerList()
        console.log('[federation] inbound link closed')
      } else if (registeredPeerId) {
        clients.delete(registeredPeerId)
        console.log(`[relay] disconnected: ${registeredPeerId.slice(0, 16)}...`)
        broadcastPeerList()
        sendLocalPeersToFedLinks()
      }
    })

    ws.on('error', (err) => {
      console.error('[relay] ws error:', err.message)
    })
  })

  // ---- Outbound federation connections ----

  for (const url of peerRelayUrls) {
    connectPeerRelay(url)
  }

  function connectPeerRelay(url, link = { ws: null, reconnectTimer: null, stopped: false }) {
    if (link.stopped) return
    outboundFedLinks.add(link)
    console.log(`[federation] connecting to ${url}...`)

    let ws
    try {
      ws = new WebSocket(url)
    } catch (err) {
      console.error(`[federation] failed to connect to ${url}:`, err.message)
      link.reconnectTimer = setTimeout(() => {
        link.reconnectTimer = null
        connectPeerRelay(url, link)
      }, 5000)
      return
    }

    link.ws = ws

    ws.on('open', () => {
      console.log(`[federation] connected to ${url}`)
      const hello = { type: 'federation:hello' }
      if (FEDERATION_SECRET) hello.secret = FEDERATION_SECRET
      ws.send(JSON.stringify(hello))
      fedLinks.set(ws, { remotePeers: new Map() })
      ws.send(JSON.stringify({ type: 'federation:peers', peers: getLocalPeers() }))
    })

    ws.on('message', (raw) => handleFedMessage(ws, raw))

    ws.on('close', () => {
      fedLinks.delete(ws)
      broadcastPeerList()
      if (link.stopped) return
      console.log(`[federation] disconnected from ${url}, reconnecting in 5s...`)
      link.reconnectTimer = setTimeout(() => {
        link.reconnectTimer = null
        connectPeerRelay(url, link)
      }, 5000)
    })

    ws.on('error', (err) => {
      console.error(`[federation] error with ${url}:`, err.message)
    })
  }

  function closeAll() {
    for (const link of outboundFedLinks) {
      link.stopped = true
      if (link.reconnectTimer) {
        clearTimeout(link.reconnectTimer)
        link.reconnectTimer = null
      }
      if (link.ws) {
        link.ws.onclose = null
        link.ws.close()
        link.ws = null
      }
    }
    outboundFedLinks.clear()
  }

  console.log(`WebSocket relay listening on port ${RELAY_PORT}`)
  if (peerRelayUrls.length > 0) {
    console.log(`Federation peers: ${peerRelayUrls.join(', ')}`)
  }

  wss.closeAll = closeAll
  return wss
}

// ===== Main =====

async function main() {
  // 1. Compute relay WebSocket URL from LAN IP (RELAY_HOST overrides auto-detect)
  let relayWsUrl = ''
  const lanIp = process.env.RELAY_HOST || '192.168.4.201'
  if (lanIp) {
    relayWsUrl = `ws://${lanIp}:${RELAY_PORT}`
    console.log(`Relay WS URL: ${relayWsUrl}`)
  }

  // 2. Generate env.ts from config
  const { gwPort, gwSecure } = generateEnvJs(relayWsUrl)

  // 3. Warn if dist/ doesn't exist (still start server so relay works)
  const distIndex = join(__dirname, 'dist', 'index.html')
  if (!existsSync(distIndex)) {
    console.warn('Warning: dist/index.html not found. Run "npm run build" to generate static files.')
  }

  // 4. Start static file server
  const staticServer = createStaticServer()
  staticServer.listen(SERVE_PORT, '0.0.0.0', () => {
    const wsProto = gwSecure ? 'wss' : 'ws'
    console.log(`\nServing eclaw-phone at http://localhost:${SERVE_PORT}`)
    console.log(`Gateway target: ${wsProto}://localhost:${gwPort}`)
  })

  // 5. Start WebSocket relay (with optional federation)
  const peerRelayUrls = (process.env.PEER_RELAYS || '')
    .split(',')
    .map(s => s.trim())
    .filter(Boolean)

  let relayWss
  try {
    relayWss = startRelayServer(peerRelayUrls)
  } catch (err) {
    console.error('Failed to start relay:', err.message)
    console.warn('P2P relay will not be available, but static serving continues.')
  }

  // 6. Graceful shutdown
  const shutdown = async (signal) => {
    console.log(`\n${signal} received. Shutting down...`)
    if (relayWss) {
      if (relayWss.closeAll) relayWss.closeAll()
      relayWss.close()
    }
    staticServer.close()
    process.exit(0)
  }

  process.on('SIGINT', () => shutdown('SIGINT'))
  process.on('SIGTERM', () => shutdown('SIGTERM'))
}

main().catch(err => {
  console.error('Server startup failed:', err)
  process.exit(1)
})
